var aufgabenPool_1_1 = [
    { format: 'quer', kontext: 'Ein Kind kauft Äpfel für 50 Cent pro Stück.', frage: 'Was ist die <strong>Ausgangsgröße</strong> in dieser Tabelle?', kopfzeile: ['', '1', '2', '3', '4', '5'], zeilen: [{ label: 'Anzahl Äpfel', werte: ['1', '2', '3', '4', '5'] }, { label: 'Preis in €', werte: ['0,50', '1,00', '1,50', '2,00', '2,50'] }], optionen: ['Zeile „Anzahl Äpfel"', 'Zeile „Preis in €"', 'Spalte 1'], richtig: 0, erklaerung: '„Anzahl Äpfel" ist die Ausgangsgröße – sie wird vorgegeben, der Preis wird daraus berechnet.' },
    { format: 'quer', kontext: 'An einem Sommertag werden Temperaturen und Eisverkäufe gemessen.', frage: 'Was ist die <strong>Ausgangsgröße</strong> in dieser Tabelle?', kopfzeile: ['', '1', '2', '3', '4'], zeilen: [{ label: 'Temperatur (°C)', werte: ['20', '25', '30', '35'] }, { label: 'Eisverkäufe (Stück)', werte: ['80', '130', '200', '280'] }], optionen: ['Zeile „Temperatur (°C)"', 'Zeile „Eisverkäufe (Stück)"', 'Spalte 2'], richtig: 0, erklaerung: 'Die Temperatur ist die Ausgangsgröße – sie ist vorgegeben, und die Eisverkäufe hängen davon ab.' },
    { format: 'quer', kontext: 'Wasser wird in einen Behälter gefüllt.', frage: 'Was ist die <strong>zugeordnete Größe</strong> in dieser Tabelle?', kopfzeile: ['', '1', '2', '3', '4', '5'], zeilen: [{ label: 'Zeit in Minuten', werte: ['1', '2', '3', '4', '5'] }, { label: 'Füllmenge in Litern', werte: ['3', '6', '9', '12', '15'] }], optionen: ['Zeile „Zeit in Minuten"', 'Zeile „Füllmenge in Litern"', 'Spalte 3'], richtig: 1, erklaerung: '„Füllmenge" ist die zugeordnete Größe – sie ergibt sich aus der verstrichenen Zeit.' },
    { format: 'quer', kontext: 'In einer Bäckerei werden Brötchen gebacken.', frage: 'Was ist die <strong>zugeordnete Größe</strong> in dieser Tabelle?', kopfzeile: ['', 'Messung 1', 'Messung 2', 'Messung 3', 'Messung 4'], zeilen: [{ label: 'Mehl in g', werte: ['200', '400', '600', '800'] }, { label: 'Anzahl Brötchen', werte: ['4', '8', '12', '16'] }], optionen: ['Zeile „Mehl in g"', 'Zeile „Anzahl Brötchen"', 'Spalte „Messung 2"'], richtig: 1, erklaerung: '„Anzahl Brötchen" ist die zugeordnete Größe – sie ergibt sich aus der Mehlmenge.' },
    { format: 'hoch', kontext: 'Schülerinnen verkaufen Kekse auf dem Schulfest.', frage: 'Was ist die <strong>Ausgangsgröße</strong> in dieser Tabelle?', spalten: ['Anzahl Kekse', 'Einnahmen in €'], zeilen: [['5','2,50'],['10','5,00'],['15','7,50'],['20','10,00']], optionen: ['Spalte „Anzahl Kekse"', 'Spalte „Einnahmen in €"', 'Zeile 1'], richtig: 0, erklaerung: '„Anzahl Kekse" ist die Ausgangsgröße – die Einnahmen ergeben sich daraus.' },
    { format: 'hoch', kontext: 'Pizzen werden in unterschiedliche Stückzahlen geteilt.', frage: 'Was ist die <strong>zugeordnete Größe</strong> in dieser Tabelle?', spalten: ['Anzahl Stücke', 'Größe eines Stücks (cm²)'], zeilen: [['4','125'],['5','100'],['8','62,5'],['10','50']], optionen: ['Spalte „Anzahl Stücke"', 'Spalte „Größe eines Stücks (cm²)"', 'Zeile 2'], richtig: 1, erklaerung: '„Größe eines Stücks" ist die zugeordnete Größe – sie hängt von der Anzahl der Stücke ab.' },
    { format: 'hoch', kontext: 'Ein Baum wird jedes Jahr älter.', frage: 'Was ist die <strong>Ausgangsgröße</strong> in dieser Tabelle?', spalten: ['Alter (Jahre)', 'Stammumfang (cm)'], zeilen: [['5','20'],['10','38'],['20','71'],['50','160']], optionen: ['Spalte „Alter (Jahre)"', 'Spalte „Stammumfang (cm)"', 'Zeile 3'], richtig: 0, erklaerung: 'Das Alter des Baums ist die Ausgangsgröße – es ist vorgegeben, und der Stammumfang hängt davon ab.' },
    { format: 'hoch', kontext: 'Strandurlauber mieten Liegestühle.', frage: 'Was ist die <strong>Ausgangsgröße</strong> in dieser Tabelle?', spalten: ['Mietdauer (Tage)', 'Kosten (€)'], zeilen: [['1','8'],['3','24'],['5','40'],['7','56']], optionen: ['Spalte „Mietdauer (Tage)"', 'Spalte „Kosten (€)"', 'Zeile 4'], richtig: 0, erklaerung: '„Mietdauer" ist die Ausgangsgröße – die Kosten ergeben sich daraus.' }
  ];

